version: '3'
services: 
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=django
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
    expose:
      - "3306"

  django:
    image: ssp04046/django-for-compose
    links:
      - db:db
    ports:
      - "8000:8000"
